export const config = {
  classes: [
    "benign",
    "bot",
    "ddos",
    "infilteration",
    //"ddos attack-hoic",
    "portscan",
    "ftp-patator",
    "ssh-patator",
    "ftp-bruteforce",
    "ssh-bruteforce",
    //"dos slowloris",
    //"dos slowhttptest",
    "dos hulk"
    //"dos goldeneye"
    //"ddos attacks-loic-http"
  ],
  features: [
    "flow duration",
    "tot fwd pkts",
    "tot bwd pkts",
    "totlen fwd pkts",
    "totlen bwd pkts",
    "fwd pkt len max",
    "fwd pkt len min",
    "fwd pkt len mean",
    "fwd pkt len std",
    "bwd pkt len max",
    "bwd pkt len min",
    "bwd pkt len mean",
    "bwd pkt len std",
    "flow byts/s",
    "flow pkts/s",
    "flow iat mean",
    "flow iat std",
    "flow iat max",
    "flow iat min",
    "fwd iat tot",
    "fwd iat mean",
    "fwd iat std",
    "fwd iat max",
    "fwd iat min",
    "bwd iat tot",
    "bwd iat mean",
    "bwd iat std",
    "bwd iat max",
    "bwd iat min",
    "fwd psh flags",
    "bwd psh flags",
    "fwd urg flags",
    "bwd urg flags",
    "bwd header len",
    "fwd pkts/s",
    "bwd pkts/s",
    "pkt len min",
    "pkt len max",
    "pkt len mean",
    "pkt len std",
    "pkt len var",
    "fin flag cnt",
    "syn flag cnt",
    "rst flag cnt",
    "psh flag cnt",
    "ack flag cnt",
    "urg flag cnt",
    "cwe flag count",
    "ece flag cnt",
    "down/up ratio",
    "pkt size avg",
    "fwd seg size avg",
    "bwd seg size avg",
    "fwd byts/b avg",
    "fwd pkts/b avg",
    "fwd blk rate avg",
    "bwd byts/b avg",
    "bwd pkts/b avg",
    "bwd blk rate avg",
    "subflow fwd byts",
    "init fwd win byts",
    "init bwd win byts",
    "fwd act data pkts",
    "fwd seg size min"
  ],
  size: 300000
};

export const defaultFeatures = [
  "flow duration",
  "tot fwd pkts",
  "tot bwd pkts",
  "totlen fwd pkts",
  "totlen bwd pkts",
  "fwd pkt len max",
  "fwd pkt len min",
  "fwd pkt len mean",
  "fwd pkt len std",
  "bwd pkt len max",
  "bwd pkt len min",
  "bwd pkt len mean",
  "bwd pkt len std",
  "flow byts/s",
  "flow pkts/s",
  "flow iat mean",
  "flow iat std",
  "flow iat max",
  "flow iat min",
  "fwd iat tot",
  "fwd iat mean",
  "fwd iat std",
  "fwd iat max",
  "fwd iat min",
  "bwd iat tot",
  "bwd iat mean",
  "bwd iat std",
  "bwd iat max",
  "bwd iat min",
  "fwd psh flags",
  "bwd psh flags",
  "fwd urg flags",
  "bwd urg flags",
  "bwd header len",
  "fwd pkts/s",
  "bwd pkts/s",
  "pkt len min",
  "pkt len max",
  "pkt len mean",
  "pkt len std",
  "pkt len var",
  "fin flag cnt",
  "syn flag cnt",
  "rst flag cnt",
  "psh flag cnt",
  "ack flag cnt",
  "urg flag cnt",
  "cwe flag count",
  "ece flag cnt",
  "down/up ratio",
  "pkt size avg",
  "fwd seg size avg",
  "bwd seg size avg",
  "fwd byts/b avg",
  "fwd pkts/b avg",
  "fwd blk rate avg",
  "bwd byts/b avg",
  "bwd pkts/b avg",
  "bwd blk rate avg",
  "subflow fwd byts",
  "init fwd win byts",
  "init bwd win byts",
  "fwd act data pkts",
  "fwd seg size min"
];
